server:
  port: 8081



spring:
  application:
      name: item-service
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/leyou
      initial-size: 5
      min-idle: 1
      max-active: 30
      test-on-borrow: true
      stat-view-servlet:
        allow: true


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**